### ISSUE TITLE
Extracting Web Technologies/Components results from an api.host() query

### ISSUE THREAD

**Issue by vamsi0914** [achillean/shodan-python#102]
Is there a way to directly access the components or web technologies section of the results from an api.host(<ip address>) query? 

For example, if you want the country name of the IP, all you have to do is 
results = api.host('ip address')
name = results('country_name') to grab the string with the name. Is there a string to get a list of all the components used in that IP (ie. Google Font API, jQuery, mySQL) and if so, what is that string? Doing components = results('components') does not work, and I am not sure what else to try there.

**Comment by achillean** [comment]
To start, you should look at the entire response that the ``api.host()`` method returns:

```python
import json
import shodan

# Get the data
api = shodan.Shodan('your api key')
info = api.host('129.121.184.163')

# Show all the information
print(json.dumps(info, indent=4, sort_keys=True))
```

Then you should see that the information you're looking for is stored in the **data** list, where all the banners are stored. And some of those banners will contain a **http.components** property. Here is some sample code for how you could extract it:

```python

# Create a list of all the web components
http_components = [tech for banner in info['data'] if 'http' in banner and 'components' in banner['http'] for tech in banner['http']['components']]

# Convert it to a set so we remove duplicates
http_components = set(http_components)
```

**Comment by vamsi0914** [comment]
Thank you so much. I think my issue was I assumed there would be a components property in every banner. Accounting for the lack of a property in some of the banners fixed my issue.

**Comment by achillean** [comment]
The properties on the banners are different depending on the type of service. As a general rule, you should always check for the existence of a property before trying to access it - even on standard ports. For example, there are SSH services running on port 80 and in those cases you won't see a **http** property but rather a **ssh* property.

Closing as it sounds like you got it working now.
