### ISSUE TITLE
Show version in the CLI

### ISSUE THREAD

**Issue by achillean** [achillean/shodan-python#104]
It isn't currently possible to identify the version of the Shodan library that's installed. We should expose either a new command (``shodan version``?) or a flag to show the version information which would help in debugging potential CLI problems and help the end-user confirm that they're running the right CLI version.

**Comment by wagner-certat** [comment]
Also possible for ASNs: https://github.com/certtools/intelmq/issues/543
And reverse DNS: https://github.com/certtools/intelmq/issues/877
See also https://github.com/certtools/intelmq/issues/373
