### ISSUE TITLE
Unicode error in domain_info

### ISSUE THREAD

**Issue by xfors** [achillean/shodan-python#106]
File "/usr/lib/python2.7/site-packages/shodan/__main__.py", line 148, in domain_info
    record['value']
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 26: ordinal not in range(128)

I fixed it locally with
--- /usr/lib/python2.7/site-packages/shodan/__main__.py
+++ /usr/lib/python2.7/site-packages/shodan/__main__.py
@@ -142,7 +142,7 @@
     click.echo('')
     for record in info['data']:
         click.echo(
-            '{:32}  {:14}  {}'.format(
+            u'{:32}  {:14}  {}'.format(
                 click.style(record['subdomain'], fg='cyan'),
                 click.style(record['type'], fg='yellow'),
                 record['value']

**Comment by fox4914** [comment]
how to solve this problem ?
![Скриншот 13-07-2019 124343](https://user-images.githubusercontent.com/52853161/61170006-15110a00-a56c-11e9-9a48-972b9cb054a6.png)

**Comment by achillean** [comment]
Thank you for the fix! It's been added to the library and is available in the latest version of the CLI.
