### ISSUE TITLE
No results for utf-8 queries

### ISSUE THREAD

**Issue by tajpmark** [achillean/shodan-python#11]
Python queries with utf-8 encoding returns 0 results. But those same strings used on the shodan website work. For example, I tried searching this (it means welcome in Chinese): 220-欢迎

More than 600 results according to shodanhq.com
But 0 results when using the Python api.

**Comment by code-bash** [comment]
Yeah having the same issue.

**Comment by achillean** [comment]
This problem has been fixed across all Shodan services! You can now search on the website/ API using special characters. For example:

https://www.shodan.io/search?query=city%3A%22S%C3%A3o+Paulo%22
