### ISSUE TITLE
Error: module 'shodan' has no attribute 'Shodan'

### ISSUE THREAD

**Issue by C4PT41ND34DP00L** [achillean/shodan-python#110]
Using python 3 I get 

Error: module 'shodan' has no attribute 'Shodan'

when running

import shodan
import sys

API_KEY = "myapikey"

if len(sys.argv) == 1:
        print ('Usage: %s <search query>' % sys.argv[0])
        sys.exit(1)

try:
  
        api = shodan.Shodan(API_KEY)

        query = ' '.join(sys.argv[1:])
        result = api.search(query)

        for service in result['matches']:
                print (service['ip_str'] + " " + service["data"])
except Exception as e:
        print ('Error: %s' % e)
        sys.exit(1)

**Comment by wagner-certat** [comment]
How did you call your file?

**Comment by C4PT41ND34DP00L** [comment]
I got it corrected. Felt stupid since I called the python file shodan.py.
