### ISSUE TITLE
Query by org via the api?

### ISSUE THREAD

**Issue by mathurin68** [achillean/shodan-python#120]
Is there a way to get the same search results from the api using python as the web dashboard? 

For example, 
Searching in the dashboard for 
https://beta.shodan.io/search?query=%22org%3A+United+States+Geological+Survey%22

I get 34 results

But if I run the search through the api I get - 
2 results 

```
try:
        # Search Shodan
        results = api.search('org: United States Geological Survey')
        # Show the results
        print('Results found: {}'.format(results['total']))
        for result in results['matches']:
#                 print('IP: {}'.format(result['ip_str']))
                print(result['ip_str'])
#                 print('')
except shodan.APIError as e:
        print('Error: {}'.format(e))

```
OR 

```
limit = 500
counter = 0
for data in api.search_cursor('org: United States Geological Survey'):
    # Perform some custom manipulations or stream the results to a database
    # For this example, I'll just print out the "data" property
#     print(data)
    print(data['org'])

    # Keep track of how many results have been downloaded so we don't use up all our query credits
    counter += 1
    if counter >= limit:
        break
    print(counter)
```

Is there a way to query this through the api?

**Comment by achillean** [comment]
Please contact support@shodan.io for these types of questions. This is related to search query syntax and not the Python library. This would be a good start to learn more about the query syntax: https://help.shodan.io/the-basics/search-query-fundamentals
