### ISSUE TITLE
Deprecation warning due to invalid escape sequences.

### ISSUE THREAD

**Issue by tirkarthi** [achillean/shodan-python#131]
Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

```
find . -iname '*.py' | grep -Ev 'rdf4|doc|benchmark|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./shodan/cli/worldmap.py:33: DeprecationWarning: invalid escape sequence \{
  'data': '''
```

**Comment by tirkarthi** [comment]
There is pylint warning but CPython has added changes to make this deprecation warning.

**Comment by achillean** [comment]
Thank you for the heads-up. Sorry for the late reply, I somehow haven't been receiving Github notifications for these new issues.

I think the easiest solution would be to just define it as a literal string.
