### ISSUE TITLE
Invalid API Key Error on msfconsole

### ISSUE THREAD

**Issue by grant21** [achillean/shodan-python#134]
I tried to search using shodan on Metasploit on Kali Linux but after copying my API key from shodan and then using the command set SHODAN_APIKEY and afterward, command 'run' it explains that my APIKEY is invalid. Please HELP!!

**Comment by sebix** [comment]
duplicate of #133

**Comment by grant21** [comment]
so how can i fix this i believe its a problem when pasting the API key but i checked for any unnecessary spaces and i didn't see any this is the code that i used in exact order `sudo su`,`msfconsole`,`search shodan`,`use auxiliary/gather/shodan_search`,`set shodan_apikey rwrztRV0N5nKECAZJW3TcjtmjfVC65gQ`,`set query "webcamxp"`,`run`

**Comment by achillean** [comment]
This isn't an issue in this Python library.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @grant21)
