### ISSUE TITLE
Move ~/.shodan folder

### ISSUE THREAD

**Issue by overclockedllama** [achillean/shodan-python#135]
Hi

Is is possible to configure shodan CLI to use a different folder other than `~/.shodan` for storing the api key? I would like to move it to `~/.config/shodan`.

As per XDG standards, all config files should be stored in `~/.config` or wherever the user has set their `$XDG_CONFIG_DIR`. I understand this isn't an XDG program, but it would be nice to be able to store all config files in the config dir.

Thanks

**Comment by achillean** [comment]
We would need to support both paths if we wanted to do this otherwise it would break existing installations. If there's a PR I'd be happy to merge it.

**Comment by overclockedllama** [comment]
Hey @achillean 

Could you please merge the PR

Thanks
