### ISSUE TITLE
Error: Searching is only available on paid accounts (membership or higher)

### ISSUE THREAD

**Issue by JettChenT** [achillean/shodan-python#138]
Don't know if this counts as an issue, but just recently when I search using the shodan CLI, for example, `shodan search "webcam"`, it shows, `Error: Searching is only available on paid accounts (membership or higher)`, while usually results will be shown.

I'm using the free API plan. Is this a change in the shodan API plans or is it something else?

**Comment by achillean** [comment]
We've already answered your question multiple times on support@shodan.io. Yes, this is a change we've had to institute for now but it's not related to the CLI or Python library.
