### ISSUE TITLE
Notice: fewer results were saved than requested

### ISSUE THREAD

**Issue by alketshabani** [achillean/shodan-python#145]
Hello,

I have a limit `--limit 5000` in my query to download data from Shodan, but i get:
`Notice: fewer results were saved than requested`,

any help would be appreciated

**Comment by gjfrommemel** [comment]
I believe this error is most likely due to free API key, which limits results to a single page.

**Comment by achillean** [comment]
Closing as not relevant. Please contact support@shodan.io. This repository is for technical discussions around the Python library - not customer support.

**Comment by nuubnuub** [comment]
Bringing this up again, as I'm **not** using the Free API (corporate), and I'm consistently getting the same truncated results. 

I'm aware that the `search()`, and `search_cursor()` methods silently fail when the API call fails, but it's to a point where I'll query the results for a single host and the count of returned results is 14, but I can only get 5 of them. If it was something like 10,000 total results but only being able to capture 8500 that's a little more understandable but, lately I can even parse 50% of the total results. 

```
API_KEY = os.environ['Shodan_API_Key']
api = Shodan(API_KEY)

query = 'hostname:my.query'
limit = api.count(query=query)['total']

logging.info(f'Total Results to Parse: {limit}')
print(f'Total Results to Parse: {limit}')

counter = 0
vuln_wanted = []

for banner in api.search_cursor(query, retries=100):  # The retries are arbitrary whether its 5 to 100 it still fails.
    counter += 1
    try:
        vuln_d = {'ip_str': banner['ip_str'],
                  'country_name': banner['location']['country_name'],
                  'longitude': banner['location']['longitude'],
                  'latitude': banner['location']['latitude'],
                  'hostnames': banner['hostnames'],
                  'vulns': banner['vulns']}
        vuln_wanted.append(vuln_d)

        logging.info(f'Vulnerability Parsed. Parsed: {counter}, Remaining: {limit - counter}')
        print(f'Vulnerability Parsed. Parsed: {counter}, Remaining: {limit - counter}')
        # Keep track of how many results have been downloaded so we don't use up all our query credits
        if counter >= limit:
            break
    except KeyError as e:

        logging.info(f'Neutral Result Parsed. Parsed: {counter}, Remaining: {limit - counter}')
        print(f'Neutral Result Parsed. Parsed: {counter}, Remaining: {limit - counter}')
        vuln_d = {'ip_str': banner['ip_str'],
                  'country_name': banner['location']['country_name'],
                  'longitude': banner['location']['longitude'],
                  'latitude': banner['location']['latitude'],
                  'hostnames': banner['hostnames']}
        vuln_wanted.append(vuln_d)
        if counter >= limit:
            break
        continue
```

The output of the results, showing how poor the search results are:
<img width="397" alt="Screenshot 2023-06-21 at 11 04 36 AM" src="https://github.com/achillean/shodan-python/assets/46011259/6d685091-959c-4497-96e5-d72de36c3e83">
And for even larger queries:
<img width="390" alt="Screenshot 2023-06-21 at 11 06 00 AM" src="https://github.com/achillean/shodan-python/assets/46011259/295f6fe8-5f9f-4009-adfa-0dd17f5bd072">
<img width="407" alt="Screenshot 2023-06-21 at 11 06 13 AM" src="https://github.com/achillean/shodan-python/assets/46011259/f7535723-9481-42e8-b56f-c4a05c816d66">

I don't know if this will get addressed, but any solution would be nice!
