### ISSUE TITLE
Gui or desktop client

### ISSUE THREAD

**Issue by hastalamuerte** [achillean/shodan-python#156]
Hello dear , developers. Thanks for your work and your product.  
 Can you plz made a desktop app or add a lightweight gui for shodan py (linux os)?

 Found a polarity and etc integrations , buts its a not a solution.  

Also there is a qshodan in snap, look ok for simple and fast use -  https://snapcraft.io/qshodan 
but have not found  it in official client lists , and not shure that it safe , cause no code audit done (?)

**Comment by achillean** [comment]
We should create a GUI at some point but that is outside the scope of this repository.
