### ISSUE TITLE
CLI reasults are diffrent from site reasults

### ISSUE THREAD

**Issue by lordofwarz** [achillean/shodan-python#157]
Hello,

When I make a search on the site it return 1M reasults but when I move the same keyword to CLI it just return 0 or any small number

the search is for example : port:443 /org:"Cloudflare, Inc."/country:"JP" 
On site : http://i.prntscr.com/ejXW0zu-RTOFkKTpLPkOXQ.png
On CLI : http://i.prntscr.com/S2ynRo2wS26jNItjspqMWg.png
Thanks in advance!!

**Comment by achillean** [comment]
You need to wrap your CLI in 2 sets of quotes. The first one is interpreted by Bash so it never gets sent to the API.
