### ISSUE TITLE
Support large XLSX files

### ISSUE THREAD

**Issue by achillean** [achillean/shodan-python#161]
The current ``shodan convert ... xlsx`` command fails on large files. We need to enable zip64 support for files to properly process files that are larger than 5GB. It looks like a simple change but need to make sure it doesn't break conversion on smaller files somehow:

https://xlsxwriter.readthedocs.io/workbook.html#use_zip64

**Comment by rmhowe425** [comment]
@achillean Are you still interested in adding this feature to the Shodan CLI?

If so, I can work on this.

**Comment by achillean** [comment]
Yes, would still love to add this!
