### ISSUE TITLE
Error: Unable to connect to Shodan

### ISSUE THREAD

**Issue by harshinsecurity** [achillean/shodan-python#174]
on trying `shodan init <api_key>` on my Kali Linux machine, I am getting error `Error: Unable to connect to Shodan`.
-> updated the requests library, still the issue persists.
![shodan_error](https://user-images.githubusercontent.com/51978908/179386172-0a7f569c-d6c3-448f-80e9-d012467b8b95.png)

**Comment by xyjxjzf** [comment]
Are you Chinese? code this in your py
`import os
os.environ["http_proxy"] = "http://127.0.0.1:10809"
os.environ["https_proxy"] = "http://127.0.0.1:10809"`

**Comment by achillean** [comment]
If you're still having connection problems please reach out to support@shodan.io . And you can use https://status.shodan.io to see if there are issues with the API at the time that you're trying to connect. Also please make sure you're running the latest version of the CLI and `requests`:

```shell
pip3 install -U shodan requests
```
