### ISSUE TITLE
Shodan no work :(

### ISSUE THREAD

**Issue by cloudcant** [achillean/shodan-python#176]
![image](https://user-images.githubusercontent.com/66269103/181408829-540daffe-2444-4cc0-94f3-eb6ac7326d7b.png)
![image](https://user-images.githubusercontent.com/66269103/181408928-06e0fccc-0d08-4e87-a9b7-d4fc85273773.png)
 
shodan is super broken for me lol any help would be appreciated

**Comment by sebix** [comment]
Looks more like an issue in your python setup. The version of urllib you have in `/home/cloud/.local/lib/python3.10` is not compatible with Python 3.10.
Try removing requests and urllib from your user-installation and install it from the system, that must be compatible.

**Comment by cloudcant** [comment]
worked :)
