### ISSUE TITLE
Loading data is incomplete

### ISSUE THREAD

**Issue by studentAlanMorgan** [achillean/shodan-python#186]
when downloading, it shows one result, it says that 100% downloaded, but saves a completely different result.
download code works for python.
script code:
#!/usr/bin/env python

import shodan
import requests
from subprocess import call

from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

def download(PATH, count, SEARCH_FOR):
s = f'{PATH} download --limit {count} shodan_data.json.gz {SEARCH_FOR} '
print(s)
call(s, shell = True)

# Configuration
PATH = "shodan"
API_KEY = "SHODAN API"
SEARCH_FOR = 'DORK'

session = requests.Session()

try:
        # Setup the api
api = shodan.Shodan(API_KEY)

        # Perform the search
count = api.count(SEARCH_FOR)['total']
print(count)
download('shodan', count, SEARCH_FOR)

except KeyboardInterrupt:
print ("Ctrl-c pressed ...")

![shodan](https://github.com/achillean/shodan-python/assets/81875252/4ee7e552-2afc-4846-9b62-6e4b4b493437)

**Comment by rmhowe425** [comment]
@studentAlanMorgan I believe that this is a known issue and is being caused by an ongoing data migration.

**Comment by achillean** [comment]
The answer from @rmhowe425 is correct. The problem has to do with banners not getting loaded fast enough from the backend database so the API skips them which can lead to early exits of the download command. The issue resolves itself once the database is fully operational again and should actually already be resolved at this point.
