### ISSUE TITLE
Is Shodan dead?

### ISSUE THREAD

**Issue by studentAlanMorgan** [achillean/shodan-python#199]
![2023-09-30_200123](https://github.com/achillean/shodan-python/assets/81875252/fb7bc4bf-05a9-4c99-8f1b-0da691270825)
Shodan is wasting credits.
I haven’t been able to download the results for a month now. results are not downloaded more than 5%.

**Comment by cachexy123** [comment]
Me too

**Comment by studentAlanMorgan** [comment]
Treatment: Before each download request, update Shodan to the latest version.
When planting, I noticed that this needs to be done constantly.

**Comment by achillean** [comment]
Update to the latest version of the CLI and please contact support@shodan.io for these sorts of issues.
