### ISSUE TITLE
ImportError: cannot import name 'Shodan' from partially initialized module 'shodan'

### ISSUE THREAD

**Issue by 2028383846** [achillean/shodan-python#208]
Hello! I encountered this error when executing after copying the official source code：
```
Traceback (most recent call last):
  File "D:\shodan.py", line 1, in <module>
    from shodan import Shodan
  File "D:\shodan.py", line 1, in <module>
    from shodan import Shodan
ImportError: cannot import name 'Shodan' from partially initialized module 'shodan' (most likely due to a circular import) (D:\shodan.py)
```
The current version of the library is: **1.30.1**

**Comment by 2028383846** [comment]
This problem has been resolved

**Comment by sebix** [comment]
Then please close the issue

**Comment by mlazzarotto** [comment]
> This problem has been resolved

@2028383846 
How did you resolve the problem?  

---

**EDIT**: I figured that out, I had to rename shodan.py to a different name.
