### ISSUE TITLE
GoogleLocation will not work after November 17, 2012.

### ISSUE THREAD

**Issue by satreix** [achillean/shodan-python#26]
In _shodan/wps.py_, the **GoogleLocation** will not work anymore.

https://code.google.com/p/gears/wiki/GeolocationAPI:

> Since Google Gears has been shut down since March 2011, the time has come to also say goodbye to the Geolocation API that powered Google Gears. The Google Gears Geolocation API will stop responding to requests on November 17, 2012.

According to [StackOverflow](http://stackoverflow.com/questions/9721213/how-could-we-get-the-location-of-wifi-tower-by-google-geolocation-service) you should look into Google [location API](https://developers.google.com/maps/documentation/geolocation/intro#wifi_access_point_object). Example:
- **POST** `https://www.googleapis.com/geolocation/v1/geolocate?key=YOUR_API_KEY`

``` json
{
 "homeMobileCountryCode": 310,
 "homeMobileNetworkCode": 260,
 "radioType": "gsm",
 "carrier": "T-Mobile",
 "cellTowers": [
  {
   "cellId": 39627456,
   "locationAreaCode": 40495,
   "mobileCountryCode": 310,
   "mobileNetworkCode": 260,
   "age": 0,
   "signalStrength": -95
  }
 ],
 "wifiAccessPoints": [
  {
   "macAddress": "01:23:45:67:89:AB",
   "signalStrength": 8,
   "age": 0,
   "signalToNoiseRatio": -65,
   "channel": 8
  }
 ]
}
```

**Comment by achillean** [comment]
The code in WPS is ancient and used an unofficial API (I think we got it from looking at how Firefox did things) so we've decided to remove wps.py as it wasn't working properly anyways due to what you mentioned.
