### ISSUE TITLE
"No open ports found or the host has been recently crawled and cant get scanned again so soon."

### ISSUE THREAD

**Issue by d33tah** [achillean/shodan-python#30]
```
$ shodan scan submit 217.113.224.201

Starting Shodan scan at 2016-09-01 16:09 - 65534 scan credits left
No open ports found or the host has been recently crawled and cant get scanned again so soon.
```

I tried many different IPs and none of them returned any different messages, yet my scan credits get deducted. Why?

**Comment by achillean** [comment]
Chances are that you scanned hosts that were recently requested by another user. And please don't use Github as a support forum; email support@shodan.io for future questions please.
