### ISSUE TITLE
Also return IPv6 address when calling shodan myip 

### ISSUE THREAD

**Issue by edermi** [achillean/shodan-python#35]
`shodan myip` currently returns only the IPv4 address of the host. Also returning the IPv6 address(es) would be a nice feature, too.

**Comment by wagner-certat** [comment]
`api.shodan.io` does only know one IP. The one you are connecting with. And as `api.shodan.io` is currently only reachable via IPv4 unfortunately the server can't know your IPv6 address.

**Comment by achillean** [comment]
As a quick comment: I would like to offer it for IPv6 but it will require some additional setup. We spoke to our hosting provider and getting 1 IPv6 address costs $2,000/ month which is insane (+ $2,000 setup fee) so it won't be available on the api.shodan.io endpoint just yet.

**Comment by achillean** [comment]
Setup a separate domain that's routed through Cloudflare to offer IPv6 support. And added a **-6** flag to the **shodan myip** command so you can do:

    shodan myip -6
