### ISSUE TITLE
Slow requests

### ISSUE THREAD

**Issue by sarandafl** [achillean/shodan-python#36]
The api is quite slow...

The uri should be updated to `api.shodan.io`, as `http://www.shodanhq.com/api/` is outdated and needs to be redirected.
The `requests` library is also quicker than `urlib`, so maybe this could be updated as well.

Both these issues I saw in `api.py`

**Comment by achillean** [comment]
The "WebAPI" class is deprecated and shouldn't be used as shodanhq.com/api doesn't exist anymore. Note that the new "Shodan" class uses the requests library.
