### ISSUE TITLE
module has no object Shodan

### ISSUE THREAD

**Issue by wandeg** [achillean/shodan-python#4]
In the implementation of the basic search example, using shodan.Shodan(SHODAN_API_KEY) throws an error.
I think it should be shodan.WebAPI(SHODAN_API_KEY)

**Comment by ManivannanMurugavel** [comment]
Please change the file name shodan.py to python_test.py or etc

**Comment by christiancoleman** [comment]
@achillean Still helping people nearly 5 years later.
