### ISSUE TITLE
worldmap depends on urllib2 (python2-only)

### ISSUE THREAD

**Issue by sebix** [achillean/shodan-python#48]
While `shodan/api.py` contains the correct imports, `shodan/cli/worldmap.py` always tries to import the python2-only module.

**Comment by achillean** [comment]
Fixed in the latest version (1.7.4) and added "shodan radar" command to make use of the world map:

https://asciinema.org/a/129227

**Comment by wagner-certat** [comment]
Looks nice!

But the git-tag is missing
