### ISSUE TITLE
Please add tags for releases

### ISSUE THREAD

**Issue by sebix** [achillean/shodan-python#53]
1.7.4 is 744ca965525ebbf04bd8db624d3f93e93d4b880f and 1.7.5 is only on pypi and not here :/

**Comment by achillean** [comment]
Added a tag for the latest release (1.7.6) and need to find a better way to automatically tag releases as they're committed to PyPi.

**Comment by wagner-certat** [comment]
Doing it manually is probably less work than automating it.

Btw: The reason I added a changelog myself now is that I couldn't easily find the changes between the versions because of missing tags...

**Comment by achillean** [comment]
Closing as there's a changelog now and releases have been tagged.
