### ISSUE TITLE
about shodan api

### ISSUE THREAD

**Issue by cuijianxiong** [achillean/shodan-python#56]
Just bought a shodan member on Black Friday.So I want to use python3 to prepare a small script about shodan,however,I can't find the search equipment about shodan api.so,I want get the shodan search api address.example:api.search("")   https://api.shodan.io/query={}&key={}

can you help me?

**Comment by wagner-certat** [comment]
http://shodan.readthedocs.io/en/latest/

**Comment by achillean** [comment]
@cuijianxiong please reach out to support@shodan.io for developer support-related questions.

**Comment by jblann** [comment]
Another good site is here https://blog.shodan.io/how-to-download-data/
