### ISSUE TITLE
Error: Invalid API key

### ISSUE THREAD

**Issue by zealsec** [achillean/shodan-python#58]
I use the command "shodan init [mykey]", and the response is "Error: Invalid API key".
My friend use the same command, he can use without any problems.

I installed shodan by "pip install shodan" in MacOS.

**Comment by alkaalysabana** [comment]
Im using termux .myfriend.in android
Pls..gv me solutions
Pada tanggal 12 Des 2017 13.33, "zealsec" <notifications@github.com>
menulis:

**Comment by achillean** [comment]
Please make sure you're running the latest version of the library:

    pip install --upgrade shodan

If there are still problems afterwards please reach out to support@shodan.io as most likely there's something wrong with your API key or it's related to your network connection.

**Comment by alkaalysabana** [comment]
Thanks...for your help ..friend...thanks
Pada tanggal 13 Des 2017 06.28, "John Matherly" <notifications@github.com>
menulis:

**Comment by zealsec** [comment]
Thx!

**Comment by amjaddon044-max** [comment]
Shodan check ho raha hai...
Error: Invalid API key

[Program finished]
