### ISSUE TITLE
problem in (api = shodan.Shodan(SHODAN_API_KEY))

### ISSUE THREAD

**Issue by EthicalHackingCOP** [achillean/shodan-python#59]
hi everybody, I'm trying to execute a python file with the next code in windows.  
>
    try:
        import shodan
    except:
        print "shodan doesn't import"

    SHODAN_API_KEY = "3JpvEP8hK266ZAPoc5FT2plFpON4hylA"

    api = shodan.Shodan(SHODAN_API_KEY)

    try:
            # Search Shodan
            results = api.search('apache')

            # Show the results
            print 'Results found: %s' % results['total']
            for result in results['matches']:
                    print 'IP: %s' % result['ip_str']
                    print result['data']
                    print ''
    except shodan.APIError, e:
            print 'Error: %s' % e

get this error:

> 
    shodan doesn't import
    Traceback (most recent call last):
      File "C:\Users\Usuario.Usuario-PC\Desktop\shodan.py", line 8, in <module>
        api = shodan.Shodan(SHODAN_API_KEY)
    NameError: name 'shodan' is not defined

Also I tried to execute it on ubuntu and i get the same error:
>
    import shodan

    SHODAN_API_KEY = "3JpvEP8hK266ZAPoc5FT2plFpON4hylA"

    api = shodan.Shodan(SHODAN_API_KEY)

    try:
            # Search Shodan
            results = api.search('apache')

            # Show the results
            print 'Results found: %s' % results['total']
            for result in results['matches']:
                    print 'IP: %s' % result['ip_str']
                    print result['data']
                    print ''
    except shodan.APIError, e:
            print 'Error: %s' % e

>
    Traceback (most recent call last):
      File "shodan.py", line 1, in <module>
        import shodan
     File "/home/user/shodan.py", line 4, in <module>
        api = shodan.Shodan(SHODAN_API_KEY)
    AttributeError: 'module' objet has no attribute 'Shodan'

What's up ?
I did install shodan from pip
(pip install shodan or easy_install shodan)

**Comment by wagner-certat** [comment]
For windows: You need to install the library first.

For Linux: The traceback looks wrong (did you mix two?)

**Comment by EthicalHackingCOP** [comment]
I did it !
This is the Windows output:

> 

    C:\Users\Usuario.Usuario-PC>pip install shodan
    Requirement already satisfied: shodan in c:\python27\lib\site-packages\shodan-1.7.7-py2.7.egg
    Requirement already satisfied: click in c:\python27\lib\site-packages (from shodan)
    Requirement already satisfied: click-plugins in c:\python27\lib\site-packages\click_plugins-1.0.3-py2.7.egg (from shodan)
    Requirement already satisfied: colorama in c:\python27\lib\site-packages\colorama-0.3.9-py2.7.egg (from shodan)
    Requirement already satisfied: requests>=2.2.1 in c:\python27\lib\site-packages\requests-2.18.4-py2.7.egg (from shodan)
    Requirement already satisfied: XlsxWriter in c:\python27\lib\site-packages\xlsxwriter-1.0.2-py2.7.egg (from shodan)
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests>=2.2.1->shodan)
    Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests>=2.2.1->shodan)
    Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests>=2.2.1->shodan)
    Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests>=2.2.1->shodan)

samely on linux ! but doesn't work :(

**Comment by EthicalHackingCOP** [comment]
FIXED

Don't use shodan as file name ! 

only install from pip or easy_install and create de file but don't rename it as shodan

**Comment by achillean** [comment]
Closing! And yes, in Python make sure not to name your script the same as a module in your PYTHONENV.
