### ISSUE TITLE
python 3 support 

### ISSUE THREAD

**Issue by L1ghtn1ng** [achillean/shodan-python#6]
Can we have python 3 support

**Comment by shangadi** [comment]
Python 2 ends by 2020. I think it is good time to start Python 3 support :-)

**Comment by achillean** [comment]
Shodan supports Python3 :) If you're unable to use it please file a bug report but I've been using it w/ Python3 for a while now.

**Comment by shangadi** [comment]
How come you are using with python3. I am unable to import the shodan module to python3. Did i miss some thing?

**Comment by shangadi** [comment]
Thank you @achillean I figured it out using shodan with python 3
