### ISSUE TITLE
Display TCP or UDP in Shodan CLI output results

### ISSUE THREAD

**Issue by razermouse** [achillean/shodan-python#64]
It would be helpful if to the right of the ports listed, Shodan would display if the port is being identified as TCP or UDP. In most cases, assuming that it's TCP isn't wrong. However, in a few cases I've seen 53 listed and thought it was likely UDP only to check the UI and find out that it's actually TCP.

Example:

Ports:
     22 OpenSSH (5.3)
     53  
     53

Mockup:

Ports:
     22 TCP OpenSSH (5.3)
     53 TCP
     53 UDP

**Comment by achillean** [comment]
Agreed! I'll be adding this info to the output.
