### ISSUE TITLE
Shodan CLI option NOT displaying SSL, TLS and banners

### ISSUE THREAD

**Issue by razermouse** [achillean/shodan-python#65]
It would be nice to be presented with a clean list of just the ports Shodan has found without the TLS/SSL and banner information on by default. 

Proposed:

# shodan host xxx.xxx.xxx.xxx

Ports:
     22 tcp 
     53 tcp
     53 udp
     80 tcp
    465 tcp
    587 tcp 
    636 tcp 
    993 tcp

(plus please see my previous post on adding the TCP/UDP flag)

# shodan --banners host xxx.xxx.xxx.xxx
Ports:
     22 tcp OpenSSH (5.3)
     53 tcp
     53 udp
     80 tcp Apache httpd (2.2.15)
    465 tcp
	|-- SSL Versions: TLSv1, TLSv1.1, TLSv1.2
	|-- Diffie-Hellman Parameters:
		Bits:          2048
		Generator:     2
    587 tcp  
	|-- SSL Versions: TLSv1, TLSv1.1
    636 tcp 
	|-- SSL Versions: SSLv3, TLSv1, TLSv1.1, TLSv1.2
	|-- Diffie-Hellman Parameters:
		Bits:          2048
		Generator:     2
    993 tcp  
	|-- SSL Versions: SSLv3, TLSv1, TLSv1.1, TLSv1.2
	|-- Diffie-Hellman Parameters:
		Bits:          1024
		Generator:     2
		Fingerprint:   RFC2409/Oakley Group 2

**Comment by achillean** [comment]
The goal of the **shodan host** command was to somewhat mimic the Nmap output. I was actually hoping to show **more** information by default (ex. how much data is stored in a DB). There already is a placeholder for different output formats which could be used to allow a "short" output format ala:

    shodan host --format=short xxx.xxx.xxx.xxx

Note that it's already possible to customize the output if you're willing to make it a 2 step process:

    shodan host -S xxx.xxx.xxx.xxx
    shodan parse --fields port,transport xxx.xxx.xxx.xxx.json.gz

**Comment by achillean** [comment]
Added new option to only print the port/ transport information. For example:

    shodan host --format tsv 8.8.8.8
