### ISSUE TITLE
Store stream data in chunks

### ISSUE THREAD

**Issue by achillean** [achillean/shodan-python#68]
Provide a new parameter in the CLI to store the data from the firehose in specified file size chunks. For example, the following command stores information in the **firehose-data** directory and once a file size gets above 100MB it creates a new data file in the directory:

    shodan stream --datadir firehose-data/ --chunk=100M

**Comment by rmhowe425** [comment]
@achillean Are you still interested in adding this to the CLI? 

I messed up my repo and had to re-fork yesterday. If you're still interested in this I can open a new PR

**Comment by achillean** [comment]
No, this actually isn't necessary anymore since we have `dstream` as a more efficient way of doing this: https://gitlab.com/shodan-public/dstream
