### ISSUE TITLE
Error: Unable to parse JSON response

### ISSUE THREAD

**Issue by joseska** [achillean/shodan-python#7]
Hello. I try to use shodan  python an always have the same error: Error: Unable to parse JSON response.

I have a Freelancer developer account and have credits remaining (more than 8000).

I try the Basic Shodan Search (https://github.com/achillean/shodan-python/blob/master/docs/examples/basic-search.rst):
# !/usr/bin/env python
# 
# shodan_ips.py
# Search SHODAN and print a list of IPs matching the query
# 
# Author: achillean

import shodan
import sys
# Configuration

API_KEY = "YOUR_API_KEY"
# Input validation

if len(sys.argv) == 1:
        print 'Usage: %s <search query>' % sys.argv[0]
        sys.exit(1)

try:
        # Setup the api
        api = shodan.Shodan(API_KEY)

```
    # Perform the search
    query = ' '.join(sys.argv[1:])
    result = api.search(query)

    # Loop through the matches and print each IP
    for service in result['matches']:
            print service['ip_str']
```

except Exception, e:
        print 'Error: %s' % e
        sys.exit(1)

**Comment by fixtrix** [comment]
fix shodan "Error: Unable to parse JSON response  --> easy_install -U requests

**Comment by CrimsonTorso** [comment]
I've had this issue for a bit until I found out it was due to there being single quotes, not double quotes. I guess Shodan's search API doesn't like ```'port:8080'```...
