### ISSUE TITLE
ValueError: invalid literal for int() with base 16: b'' when testing the 'private firehose' demo

### ISSUE THREAD

**Issue by swedishmike** [achillean/shodan-python#76]
Hi,

I was testing the [Network alerts](https://help.shodan.io/guides/how-to-monitor-network) functionality when I ran across an error. 

I've now had the same error twice so it looks like it is repeatable:

> Traceback (most recent call last):
>   File "/root/shodan/venv/lib/python3.5/site-packages/urllib3/response.py", line 572, in _update_chunk_length
>     self.chunk_left = int(line, 16)
> ValueError: invalid literal for int() with base 16: b''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/shodan/venv/lib/python3.5/site-packages/urllib3/response.py", line 331, in _error_catcher
>     yield
>   File "/root/shodan/venv/lib/python3.5/site-packages/urllib3/response.py", line 637, in read_chunked
>     self._update_chunk_length()
>   File "/root/shodan/venv/lib/python3.5/site-packages/urllib3/response.py", line 576, in _update_chunk_length
>     raise httplib.IncompleteRead(line)
> http.client.IncompleteRead: IncompleteRead(0 bytes read)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/shodan/venv/lib/python3.5/site-packages/requests/models.py", line 749, in generate
>     for chunk in self.raw.stream(chunk_size, decode_content=True):
>   File "/root/shodan/venv/lib/python3.5/site-packages/urllib3/response.py", line 461, in stream
>     for line in self.read_chunked(amt, decode_content=decode_content):
>   File "/root/shodan/venv/lib/python3.5/site-packages/urllib3/response.py", line 665, in read_chunked
>     self._original_response.close()
>   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/root/shodan/venv/lib/python3.5/site-packages/urllib3/response.py", line 349, in _error_catcher
>     raise ProtocolError('Connection broken: %r' % e, e)
> urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "monitornetwork_ports.py", line 17, in <module>
>     for banner in api.stream.alert():
>   File "/root/shodan/venv/lib/python3.5/site-packages/shodan/stream.py", line 79, in alert
>     for line in self._iter_stream(stream, raw):
>   File "/root/shodan/venv/lib/python3.5/site-packages/shodan/stream.py", line 63, in _iter_stream
>     for line in stream.iter_lines(decode_unicode=True):
>   File "/root/shodan/venv/lib/python3.5/site-packages/requests/models.py", line 793, in iter_lines
>     for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
>   File "/root/shodan/venv/lib/python3.5/site-packages/requests/utils.py", line 503, in stream_decode_response_unicode
>     for chunk in iterator:
>   File "/root/shodan/venv/lib/python3.5/site-packages/requests/models.py", line 752, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by wagner-certat** [comment]
`Connection broken` / `IncompleteRead` is a quite common error for network interruptions and similar network issues.

**Comment by wagner-certat** [comment]
The last error in the traceback is the relevant one. The top one is an internal error in the http lib. It results in the human-understandable `ChunkedEncodingError`/`Connection broken` error.

**Comment by swedishmike** [comment]
Ahh.. Ok. 

I'll close this one for now then - and enable further monitoring on the host to see if there is loss of connectivity the next time this error shows up. If there indeed is another occurrence.

Thanks for your help and feedback!
