### ISSUE TITLE
official github release for 1.10.1

### ISSUE THREAD

**Issue by xorond** [achillean/shodan-python#79]
hi, is it possible to add this? it already exists on pypi.
thanks.

**Comment by achillean** [comment]
Done :)

**Comment by xorond** [comment]
release name is wrong on the title (says 1.10.0), although the source is correct.

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/a4f9566aac17fb1280b91426a7ef8a7ed2197b31

thanks :)

**Comment by achillean** [comment]
Fixed :) Thanks!
