### ISSUE TITLE
--help Bug

### ISSUE THREAD

**Issue by CarlosLannister** [achillean/shodan-python#8]
When you do shodan --help the results are:

Commands:
  count     Returns the number of results for a search
  download  Download search results and save them in a...
  init      Initialize the Shodan command-line
  myip      Print your external IP address
  parse     Extract information out of compressed JSON...
  scan      Returns the number of results for a search
  search    Search the Shodan database

The Scan info should be Scan a network using Shodan.  

github.com/achillean/shodan-python/blob/8258321b8e7d6f9b320dd30c05931c0e4c32d4ab/bin/shodan#L234

**Comment by achillean** [comment]
Thanks for finding that! Just fixed it with the latest check-in:

https://github.com/achillean/shodan-python/blob/master/bin/shodan#L234
