### ISSUE TITLE
Query Result Download Limitations

### ISSUE THREAD

**Issue by RoboGeek123** [achillean/shodan-python#92]
**1**. When using the CLI or web GUI, I am only able to download a portion of the results.

_Example 1_
![image](https://user-images.githubusercontent.com/40606082/51628589-63294700-1f13-11e9-85e4-feb7f7cdd8fa.png)

_Example 2_
![image](https://user-images.githubusercontent.com/40606082/51628701-b69b9500-1f13-11e9-9e95-daf8bc3e221d.png)

**2.**  Reports section of Web GUI appears to be glitching and shows no reports despite the fact that I have indeed created reports in the past.  All I get is this page 
![image](https://user-images.githubusercontent.com/40606082/51628559-4c82f000-1f13-11e9-8b2a-4896c8055893.png)[image]

**Comment by achillean** [comment]
The database cluster had a partial outage which caused what you observed. The service should be fully operational again by now. In the future, please send these types of issues to support@shodan.io - this repository is for the development of the Python library/ CLI.

**Comment by RoboGeek123** [comment]
Whoops.  My mistake!  Will do in the future.  Thank you for the speedy
response and fix
