### ISSUE TITLE
Is there a way to enable and change triggers for an alert through the API instead of the command-line utility?  I don't see one in the API docs or the shodan-python docs

### ISSUE THREAD

**Issue by scumola** [achillean/shodan-python#95]
Is there a way to enable and change triggers for an alert through the API instead of the command-line utility?  I don't see one in the API docs or the shodan-python docs.

I want the equivalent of "shodan alert xxxxxx enable any" but in the python API.

**Comment by scumola** [comment]
NM, I found how to do this by searching the CLI source code.  Should be added to the docs though.

**Comment by achillean** [comment]
Yes, you're right! We've been focused on the new API functionality and Shodan Monitor website but we will be updating the documentation to reflect the new capabilities. There are a few more things we will be adding to the API though before we finalize the documentation.
