### ISSUE TITLE
Streaming alerts not triggering unless --alert=id.  --alert=all not working in cli, also not working in API

### ISSUE THREAD

**Issue by scumola** [achillean/shodan-python#96]
When I enabled an alert and triggered on 'any', I got an email, but my script to monitor the alert didn't get a notification.  :(

My monitoring script (which seems to never trigger) - also never triggers if the my_alert_id is omitted:
```#!/usr/bin/python
from shodan import Shodan
import json

api = Shodan('xxxxxx')
for alert in api.stream.alert("my_alert_id"):
    print json.dumps(alert, sort_keys=True, indent=2, separators=(',', ':'))

**Comment by scumola** [comment]
Ok, worded better:

Works:
shodan alert --alert=xxxxxx
Doesn't work:
shodan alert --alert=all

code to grab the alert stream, but not actually alerting:
```#!/usr/bin/python
from shodan import Shodan
import json

api = Shodan('xxxxxxx')
alert_id = 0

results = api.alerts()
for alert in results:
    print "Alert: ", alert['id'], alert['name'], alert['triggers']
    alert_id = alert['id']

for alert in api.stream.alert(alert_id):
    print json.dumps(alert, sort_keys=True, indent=2, separators=(',', ':'))

**Comment by achillean** [comment]
Are you still experiencing this problem? We use the functionality internally and haven't had problems. This doesn't look like it's an issue with the CLI/ Python library so I'm closing the issue. Please reach out to support@shodan.io if you continue having problems accessing the network alerts stream.
